# 실패 유형별로 재실행할 Agent를 매핑합니다.

FAILURE_AGENT_MAP: dict[str, list[str]] = {
    "DOCUMENT_MERGE_OUTPUT_MISSING": ["document_merge_agent"],
    "SRS_OUTPUT_MISSING": ["requirement_generation_agent"],
    "SRS_SCHEMA_ERROR": ["requirement_generation_agent"],
    "SRS_REQUIRED_FIELD_MISSING": ["requirement_generation_agent"],
    "SRS_DUPLICATE_REQ_ID": ["requirement_generation_agent"],
    "SRS_DUPLICATE_REQUIREMENT": ["requirement_generation_agent"],
    "SRS_SOURCE_TRACE_MISSING": ["document_merge_agent", "requirement_generation_agent"],
    "SRS_MEETING_CHANGE_MISSING": [
        "document_merge_agent",
        "requirement_generation_agent",
    ],
    "SRS_NON_FUNCTIONAL_MISSING": ["requirement_generation_agent"],
    "SRS_WORK_UNIT_INVALID": ["requirement_generation_agent"],
    "INTERFACE_OUTPUT_MISSING": ["image_analysis_agent"],
    "INTERFACE_SCHEMA_ERROR": ["image_analysis_agent"],
    "INTERFACE_SCREEN_ID_DUPLICATED": ["image_analysis_agent"],
    "INTERFACE_REQUIREMENT_MAPPING_MISSING": ["document_merge_agent", "image_analysis_agent"],
    "INTERFACE_IMAGE_MAPPING_MISSING": ["image_analysis_agent"],
    "INTERFACE_DESCRIPTION_MISSING": ["image_analysis_agent"],
    "INTERFACE_UX_GUIDE_NOT_REFLECTED": ["image_analysis_agent"],
    "INTERFACE_IMAGE_STATUS_INVALID": ["image_analysis_agent"],
    "INTERFACE_IMAGE_UPDATE_MESSAGE_MISSING": ["image_analysis_agent"],
    "TS_OUTPUT_MISSING": ["test_scenario_generation_agent"],
    "TS_SCHEMA_ERROR": ["test_scenario_generation_agent"],
    "TS_SCENARIO_ID_DUPLICATED": ["test_scenario_generation_agent"],
    "TS_TEST_CASE_ID_DUPLICATED": ["test_scenario_generation_agent"],
    "TS_STEP_MISSING": ["test_scenario_generation_agent"],
    "TS_STEP_DETAIL_MISSING": ["test_scenario_generation_agent"],
    "TS_REQUIREMENT_COVERAGE_MISSING": ["document_merge_agent", "test_scenario_generation_agent"],
    "TS_INTERFACE_MAPPING_MISSING": [
        "document_merge_agent",
        "test_scenario_generation_agent",
    ],
    "TS_NORMAL_CASE_MISSING": ["test_scenario_generation_agent"],
    "TS_EXCEPTION_CASE_MISSING": ["test_scenario_generation_agent"],
    "TS_TRACEABILITY_MISSING": ["test_scenario_generation_agent"],
    "TS_MEETING_CHANGE_MISSING": ["document_merge_agent", "test_scenario_generation_agent"],
    "ERD_OUTPUT_MISSING": ["data_structure_design_agent"],
    "ERD_SCHEMA_ERROR": ["data_structure_design_agent"],
    "ERD_TABLE_DUPLICATED": ["data_structure_design_agent"],
    "ERD_COLUMN_DUPLICATED": ["data_structure_design_agent"],
    "ERD_PK_MISSING": ["data_structure_design_agent"],
    "ERD_FK_INVALID": ["data_structure_design_agent"],
    "ERD_REQUIREMENT_COVERAGE_MISSING": ["document_merge_agent", "data_structure_design_agent"],
    "ERD_STANDARD_NAMING_ERROR": ["data_structure_design_agent"],
    "ERD_MEETING_CHANGE_MISSING": ["data_structure_design_agent"],
    "ERD_MERMAID_CODE_MISSING": ["mermaid_generation_agent"],
    "ERD_MERMAID_RENDER_FAILED": ["mermaid_generation_agent"],
    "ERD_MERMAID_COVERAGE_MISSING": ["mermaid_generation_agent"],
    "ENTITY_GENERIC_NAME": ["data_structure_design_agent"],
    "ENTITY_NAME_MISMATCH": ["data_structure_design_agent"],
    "ENTITY_ATTRIBUTE_MISMATCH": ["data_structure_design_agent"],
    "ENTITY_DESCRIPTION_MISMATCH": ["data_structure_design_agent"],
    "ENTITY_NAME_MISSING": ["data_structure_design_agent"],
    "ENTITY_NAME_OVERLONG": ["data_structure_design_agent"],
    "ENTITY_NAME_SENTENCE": ["data_structure_design_agent"],
    "ENTITY_SEMANTIC_DUPLICATED": ["data_structure_design_agent"],
    "ERD_ENTITY_NAME_INCONSISTENT": ["data_structure_design_agent", "mermaid_generation_agent"],
    "ERD_KEY_FLAG_FORMAT_INVALID": ["data_structure_design_agent"],
    "RELATION_TABLE_MISSING": ["data_structure_design_agent"],
    "RELATION_COLUMN_MISSING": ["data_structure_design_agent"],
    "RELATION_KEY_MISMATCH": ["data_structure_design_agent"],
    "FK_RELATION_MISSING": ["data_structure_design_agent"],
    "COMMON_COLUMN_OVERUSE": ["data_structure_design_agent"],
    "STANDALONE_ENTITY_EXCESSIVE": ["data_structure_design_agent"],
    "DB_OUTPUT_MISSING": ["data_structure_design_agent"],
    "DB_SCHEMA_ERROR": ["data_structure_design_agent"],
    "DB_TABLE_MISSING": ["data_structure_design_agent"],
    "DB_COLUMN_MISSING": ["data_structure_design_agent"],
    "DB_DATA_TYPE_MISSING": ["data_structure_design_agent"],
    "DB_CONSTRAINT_INVALID": ["data_structure_design_agent"],
    "DB_INDEX_INVALID": ["data_structure_design_agent"],
    "DB_DDL_INVALID": ["data_structure_design_agent"],
    "DB_TABLE_ID_UNRESOLVED": ["data_structure_design_agent"],
    "DB_TABLE_ID_MAPPING_INVALID": ["data_structure_design_agent"],
    "DB_TABLESPACE_ID_INVALID": ["data_structure_design_agent"],
    "DB_TABLESPACE_MAPPING_INVALID": ["data_structure_design_agent"],
    "DB_TABLE_ENTITY_MAPPING_INVALID": ["data_structure_design_agent"],
    "DB_TABLE_NAME_DUPLICATED": ["data_structure_design_agent"],
    "DB_TABLE_SEMANTIC_DUPLICATED": ["data_structure_design_agent"],
    "DB_MEETING_CHANGE_MISSING": ["document_merge_agent", "data_structure_design_agent"],
    "ARCH_OUTPUT_MISSING": ["architecture_analysis_agent"],
    "ARCH_SCHEMA_ERROR": ["architecture_analysis_agent"],
    "ARCH_COMPONENT_DUPLICATED": ["architecture_analysis_agent"],
    "ARCH_RELATION_MISSING": ["architecture_analysis_agent"],
    "ARCH_COMPONENT_ISOLATED": ["architecture_analysis_agent"],
    "ARCH_CONFIG_NOT_REFLECTED": ["architecture_analysis_agent"],
    "ARCH_NON_FUNCTIONAL_MISSING": ["architecture_analysis_agent"],
    "ARCH_MERMAID_CODE_MISSING": ["mermaid_generation_agent"],
    "ARCH_MERMAID_RENDER_FAILED": ["mermaid_generation_agent"],
    "ARCH_MEETING_CHANGE_MISSING": ["document_merge_agent", "architecture_analysis_agent"],
}


def get_failure_agents(failure_type: str) -> list[str]:
    return list(FAILURE_AGENT_MAP.get(failure_type, []))
