# 산출물 검증 실패 코드를 정의합니다.

MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_DOCS_CD = "INVALID_DOCS_CD"
INVALID_UDT_YN = "INVALID_UDT_YN"
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
FILE_NOT_FOUND = "FILE_NOT_FOUND"
REQUIRED_FILE_MISSING = "REQUIRED_FILE_MISSING"
REQUIRED_REFERENCE_MISSING = "REQUIRED_REFERENCE_MISSING"
PREPROCESS_FAILED = "PREPROCESS_FAILED"
